version: "3.7"

services:
    db_postgres: 
        image: postgres:10
        container_name: db_postgres
        environment:
            POSTGRES_PASSWORD: 'Password@123'
            POSTGRES_USER: 'pgsql_user'
            POSTGRES_DB: 'recipe_book'
        ports: 
        - 5432:5432
    api:
        build: ./API
        container_name: api
        environment: 
          - SPRING_PROFILES_ACTIVE=devel
        expose:
          - "8080"
        ports:
          - 8080:8080
        depends_on:
          - db_postgres
    ui:
        build: ./UI
        container_name: ui
        ports:
          - 80:4200
        depends_on:
          - api